---
title: "Open Source License"
bibliography: ../quarto_site/references.bib
---

This repository is licensed under a GPL-3.0 license.

::: {.callout-note appearance="minimal" collapse=true}

## View license

{{< include  ../LICENSE >}}

:::

This is aligned with the original study, who shared their code under a GPL-3.0 license.

::: {.callout-note appearance="minimal" collapse=true}

## View license

{{< include  ../original_study/desECR/LICENSE >}}

:::

The original study was published in the journal "Frontiers in Neurology". They distributed the article under a CC-BY license.

::: {.callout-note appearance="minimal" collapse=true}

## View copyright statement from journal

From <https://doi.org/10.3389/fneur.2019.00653>:

“© 2019 Huang, Maingard, Kok, Barras, Thijs, Chandra, Brooks and Asadi. This is an open-access article distributed under the terms of the Creative Commons Attribution License (CC BY). The use, distribution or reproduction in other forums is permitted, provided the original author(s) and the copyright owner(s) are credited and that the original publication in this journal is cited, in accordance with accepted academic practice. No use, distribution or reproduction is permitted which does not comply with these terms.”

:::
