---
title: Reproduction
output: html_document
---

# Reproduction

## Set up

```{r}
# Clear environment
rm(list=ls())

# Start timer
start.time <- Sys.time()

# Disable scientific notation
options(scipen=999)

# Get the model function (but hide loading warnings for each package)
suppressMessages(source("model.R"))
```

This function was created to reduce code duplication, with the baseline model parameters as inputs...
  
```{r}
run_model <- function(angio_inr = 1,
                      ir = 2,
                      angio_staff = 6,
                      ed_pt = 107700,
                      inr_pt = 104,
                      eir_pt= 468,
                      ir_pt = 3805,
                      run_t = 365,
                      nsim = 30,
                      exclusive_use = FALSE,
                      seed = 42) {
  #' Run model and get results
  #' 
  #' @param angio_inr number of AngioINR machines
  #' @param ir number of interventional radiologists on day shift
  #' @param angio_staff number of angiography staff on day shift
  #' @param ed_pt number of ED patients
  #' @param inr_pt number of elective INR patients
  #' @param eir_pt number of emergency IR patients
  #' @param ir_pt number of elective IR patients
  #' @param run_t simulation runtime in days
  #' @param nsim number of replications
  #' @param exclusive_use whether angioINR has exclusive use (i.e. no elective
  #' IR patients allowed to use the machine)
  #' @param seed integer that provides seed to be incremented on in each
  #' replication (e.g. run 1 is seed+=1, run 2 is seed+=2)

  # Run the model
  list_containing_output <- simulate_nav(
    angio_inr = angio_inr,
    ir = ir,
    angio_staff = angio_staff,
    ed_pt = ed_pt,
    inr_pt = inr_pt,
    eir_pt = eir_pt,
    ir_pt = ir_pt,
    run_t = run_t,
    nsim = nsim,
    exclusive_use = exclusive_use,
    seed = seed
  )
  # Get arrivals and resources
  arrivals <- data.frame(list_containing_output[[1]])
  resources <- list_containing_output[[2]]

  # Return list with two dataframes
  return(list(arrivals, resources))
}
```

## Run model

Run through each of the scenarios

```{r}
baseline <- run_model(seed=100)
```

```{r}
baseline <- run_model(nsim=3, seed=100)
```

```{r}
baseline2 <- run_model(seed=100)
```

```{r}
# Loop through the dataframes and present the mean wait time for each resource
# (across all replications)
df_list <- list(baseline[[1]], baseline2[[1]])
for (i in 1:length(df_list)) {
  print(df_list[[i]] %>%
    filter(category == "ed") %>%
    group_by(resource) %>%
    summarize("mean" = mean(wait_time),
              "median" = median(wait_time)))
}
```

```{r}
exclusive <- run_model(exclusive_use = TRUE)
```

```{r}
twoangio <- run_model(angio_inr = 2)
```

### Results

```{r}
print(head(baseline[[1]], 5))
print(head(exclusive[[1]], 5))
print(head(twoangio[[1]], 5))
```

```{r}
base_arrivals <- baseline[[1]]
unique(base_arrivals$category)
```

```{r}
# Loop through the dataframes and present the mean wait time for each resource
# (across all replications)
df_list <- list(baseline[[1]], exclusive[[1]], twoangio[[1]])
for (i in 1:length(df_list)) {
  print(df_list[[i]] %>%
    filter(category == "ed") %>%
    group_by(resource) %>%
    summarize("mean" = mean(wait_time),
              "median" = median(wait_time)))
}
```

## Time elapsed

```{r}
end.time <- Sys.time()
elapsed.time <- round((end.time - start.time), 3)
elapsed.time
```
