<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amy Heather">
<meta name="dcterms.date" content="2024-07-10">

<title>Day 6 – Reproducing Huang et al.&nbsp;2019</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../quarto_site/stars_logo_blue.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-c75bcb89907db7808f0349b764a1a524.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../quarto_site/stars_logo_blue.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Reproducing Huang et al.&nbsp;2019</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../quarto_site/study_publication.html"> 
<span class="menu-text">Original study</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-reproduction" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Reproduction</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-reproduction">    
        <li>
    <a class="dropdown-item" href="../../../quarto_site/reproduction_readme.html">
 <span class="dropdown-text">README</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-evaluation" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Evaluation</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-evaluation">    
        <li>
    <a class="dropdown-item" href="../../../evaluation/scope.html">
 <span class="dropdown-text">Scope</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../evaluation/reproduction_success.html">
 <span class="dropdown-text">Reproduction success</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../evaluation/badges.html">
 <span class="dropdown-text">Journal badges</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../evaluation/artefacts.html">
 <span class="dropdown-text">STARS framework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../evaluation/reporting.html">
 <span class="dropdown-text">Reporting guidelines</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../logbook/logbook.html"> 
<span class="menu-text">Logbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../evaluation/reproduction_report.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../evaluation/reflections.html"> 
<span class="menu-text">Reflections</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pythonhealthdatascience/stars-reproduce-huang-2019"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Day 6</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">reproduce</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Amy Heather </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 10, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#going-back-to-the-app" id="toc-going-back-to-the-app" class="nav-link active" data-scroll-target="#going-back-to-the-app">09.18-09.25: Going back to the app</a></li>
  <li><a href="#running-the-model-with-default-parameters-from-the-code" id="toc-running-the-model-with-default-parameters-from-the-code" class="nav-link" data-scroll-target="#running-the-model-with-default-parameters-from-the-code">09.26-09.32, 09.38-9.40, 10.09-10.12: Running the model with default parameters from the code</a></li>
  <li><a href="#in-middle-of-the-above-discussion-with-tom" id="toc-in-middle-of-the-above-discussion-with-tom" class="nav-link" data-scroll-target="#in-middle-of-the-above-discussion-with-tom">09.42-10.00 (in middle of the above): Discussion with Tom</a></li>
  <li><a href="#check-the-inter-arrival-times" id="toc-check-the-inter-arrival-times" class="nav-link" data-scroll-target="#check-the-inter-arrival-times">10.31-10.36: Check the inter-arrival times</a></li>
  <li><a href="#check-distributions-and-length-of-resources" id="toc-check-distributions-and-length-of-resources" class="nav-link" data-scroll-target="#check-distributions-and-length-of-resources">10.51-12.02, 12.12-12.15: Check distributions and length of resources</a>
  <ul class="collapse">
  <li><a href="#emergency-arrival-patient-sampling-distributions-length" id="toc-emergency-arrival-patient-sampling-distributions-length" class="nav-link" data-scroll-target="#emergency-arrival-patient-sampling-distributions-length">Emergency arrival patient sampling / distributions / length</a></li>
  <li><a href="#other-patients" id="toc-other-patients" class="nav-link" data-scroll-target="#other-patients">Other patients</a></li>
  <li><a href="#reflections-from-this" id="toc-reflections-from-this" class="nav-link" data-scroll-target="#reflections-from-this">Reflections from this</a></li>
  </ul></li>
  <li><a href="#varying-ed-triage-length" id="toc-varying-ed-triage-length" class="nav-link" data-scroll-target="#varying-ed-triage-length">13.00-13.15: Varying ED triage length</a></li>
  <li><a href="#double-check-category-being-presented" id="toc-double-check-category-being-presented" class="nav-link" data-scroll-target="#double-check-category-being-presented">13.16-13.28: Double check category being presented</a></li>
  <li><a href="#double-check-inr-room-options" id="toc-double-check-inr-room-options" class="nav-link" data-scroll-target="#double-check-inr-room-options">13.39-13.43: Double-check INR room options</a></li>
  <li><a href="#vary-length-of-resources-to-try-to-engineer-results" id="toc-vary-length-of-resources-to-try-to-engineer-results" class="nav-link" data-scroll-target="#vary-length-of-resources-to-try-to-engineer-results">13.44-14.10, 14.15-14.45: Vary length of resources to try to engineer results</a></li>
  <li><a href="#looking-into-figure-2c-and-3c-and-getting-in-text-result-2" id="toc-looking-into-figure-2c-and-3c-and-getting-in-text-result-2" class="nav-link" data-scroll-target="#looking-into-figure-2c-and-3c-and-getting-in-text-result-2">16.03-16.19: Looking into Figure 2C and 3C, and getting in-text result 2!</a></li>
  <li><a href="#trying-to-raise-the-angioinr-queues" id="toc-trying-to-raise-the-angioinr-queues" class="nav-link" data-scroll-target="#trying-to-raise-the-angioinr-queues">16.25-17.00: Trying to raise the angioINR queues</a></li>
  <li><a href="#timings" id="toc-timings" class="nav-link" data-scroll-target="#timings">Timings</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/pythonhealthdatascience/stars-reproduce-huang-2019/edit/main/logbook/posts/2024_07_10/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/pythonhealthdatascience/stars-reproduce-huang-2019/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reproduced in-text 2, working on Figures 2 + 3. Total time used: 20h 28m (51.2%).</p>
</div>
</div>
<section id="going-back-to-the-app" class="level2">
<h2 class="anchored" data-anchor-id="going-back-to-the-app">09.18-09.25: Going back to the app</h2>
<p>Although the figures in the app don’t match up to the figures in the paper, I wanted to check to see if I could get any more similar results via the app.</p>
<p>Could put in all the parameters, except number of simulations was limited to 10 (rather than 30) but crashes at that number, so run at their default. However, the outputs don’t really contain anything usable (e.g.&nbsp;just know most had short wait time, and know median occupancy ratio was around 20%). However, it did make me think that’s it’s worth trying the models with the default parameters from the code (rather than the paper), just to see if that happens to look any more similar.</p>
</section>
<section id="running-the-model-with-default-parameters-from-the-code" class="level2">
<h2 class="anchored" data-anchor-id="running-the-model-with-default-parameters-from-the-code">09.26-09.32, 09.38-9.40, 10.09-10.12: Running the model with default parameters from the code</h2>
<p>Ran baseline model with default parameters from the code (rather than fixing to meet paper).</p>
<p>Interesting differences, for example, are that it is 1 simulation (<code>nsim=1</code>) but run time 10,000 days (<code>run_t=10000</code>) which works out to about 27 years (which is not far off running 30 simulations each of 1 year).</p>
<p>However, can see this is absolutely wrong! Which is not surprising, but still good we checked.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_codeparam.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2A with parameters from code</figcaption>
</figure>
</div>
</section>
<section id="in-middle-of-the-above-discussion-with-tom" class="level2">
<h2 class="anchored" data-anchor-id="in-middle-of-the-above-discussion-with-tom">09.42-10.00 (in middle of the above): Discussion with Tom</h2>
<p>Showed Tom the progress and he shared from additional suggestions of things to look into:</p>
<ul>
<li>Check calculated inter-arrival times match paper</li>
<li>Check distributions are the same</li>
<li>Check length of resources (we realised not mentioned in paper - e.g.&nbsp;timeout for appointment)</li>
</ul>
<p>Also, reminded that the use of simEd and seed streams is not about getting the same results from the same model with the same parameters, but about controlling change when you change parameters (i.e.&nbsp;so the only thing that changes is that parameter, and not the sampling). However, in this case, <code>set.seed()</code> is sufficient.</p>
<p>My additional reflections of things to try from this are to:</p>
<ul>
<li>Vary length of resources</li>
<li>Try not limiting to just ED patients</li>
<li>Double-check if INR procedures only have one room option (whilst IR have two rooms)</li>
<li>Look at parameters used in the diagram on CLOUDES</li>
</ul>
<p>Agreed to explore these and anything else can think of, but if then still stuck, at that point to email the authors (once have tried the final figures - resource utilisation and supplementary).</p>
<p>Felt could then move into evaluation against guidelines - in protocol, had mentioned waiting until after fully wrapped with the model, with rationale that it impacts on code timings, but on reflection, you could argue likewise for influence on timings of that evaluation if you waited before proceeding to it (e.g.&nbsp;waiting for response) and had then had a gap from working on that model and were no longer as familiar.</p>
</section>
<section id="check-the-inter-arrival-times" class="level2">
<h2 class="anchored" data-anchor-id="check-the-inter-arrival-times">10.31-10.36: Check the inter-arrival times</h2>
<div id="ffaa1e5a" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set in reproduction.qmd</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>ed_pt <span class="op">=</span> <span class="dv">107700</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>inr_pt <span class="op">=</span> <span class="dv">104</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>eir_pt <span class="op">=</span> <span class="dv">468</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>ir_pt <span class="op">=</span> <span class="dv">3805</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set in model.R</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>st_pt <span class="op">=</span> <span class="dv">750</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>ais_pt <span class="op">=</span> <span class="dv">450</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>ecr_pt <span class="op">=</span> <span class="dv">58</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate inter-arrival times (as from model.R)</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>year2min <span class="op">=</span> <span class="dv">525600</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>I_ED  <span class="op">=</span> <span class="bu">round</span>(year2min <span class="op">/</span> ed_pt)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>I_ST  <span class="op">=</span> <span class="bu">round</span>(year2min <span class="op">/</span> st_pt)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>I_AIS <span class="op">=</span> <span class="bu">round</span>(year2min <span class="op">/</span> ais_pt)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>I_ECR <span class="op">=</span> <span class="bu">round</span>(year2min <span class="op">/</span> ecr_pt)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>I_INR <span class="op">=</span> <span class="bu">round</span>(year2min <span class="op">/</span> inr_pt)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>I_EIR <span class="op">=</span> <span class="bu">round</span>(year2min <span class="op">/</span> eir_pt)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>I_IR  <span class="op">=</span> <span class="bu">round</span>(year2min <span class="op">/</span> ir_pt)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># View calculated inter-arrival times</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>([I_ED, I_ST, I_AIS, I_ECR, I_INR, I_EIR, I_IR])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[5, 701, 1168, 9062, 5054, 1123, 138]</code></pre>
</div>
</div>
<p>These match up with the times from the paper, as in the image below from <span class="citation" data-cites="huang_optimizing_2019">Huang et al. (<a href="#ref-huang_optimizing_2019" role="doc-biblioref">2019</a>)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../../../original_study/tab1.jpg" class="img-fluid figure-img"></p>
<figcaption>Table 1</figcaption>
</figure>
</div>
</section>
<section id="check-distributions-and-length-of-resources" class="level2">
<h2 class="anchored" data-anchor-id="check-distributions-and-length-of-resources">10.51-12.02, 12.12-12.15: Check distributions and length of resources</h2>
<p>As a reminder, this is the set-up of the model, with Figure 1 from <span class="citation" data-cites="huang_optimizing_2019">Huang et al. (<a href="#ref-huang_optimizing_2019" role="doc-biblioref">2019</a>)</span>. There are several resources, including single plane (angioIR) and biplane (angioINR) angiography suites.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../../original_study/fig1.jpg" class="img-fluid figure-img"></p>
<figcaption>Figure 1</figcaption>
</figure>
</div>
<p>Emergency arrival (potential stroke) patients:</p>
<ul>
<li>Start as emergency arrival (<code>new_patient_traj</code>)</li>
<li>Become either a stroke patient (<code>stroke_traj</code>) or non-stroke patient (<code>nonstroke_traj</code>)</li>
<li>The stroke patients will then become either AIS (acute ischaemic stroke) (<code>ais_traj</code>) or non-AIS (timeout then leave)</li>
<li>The AIS patients will then become either ECR (endovascular clot retrieval) (<code>ecr_traj</code>) or TPA (tissue plasminogen activator) only (timeout then leave)</li>
</ul>
<p>Other patients (pathways included as they share resources with stroke pathway):</p>
<ul>
<li>Interventional radiology patients (<code>ir_traj</code>)</li>
<li>Emergency interventional radiology patients (<code>eir_traj</code>)</li>
<li>Interventional neuroradiology patients (<code>inr_traj</code>)</li>
</ul>
<section id="emergency-arrival-patient-sampling-distributions-length" class="level3">
<h3 class="anchored" data-anchor-id="emergency-arrival-patient-sampling-distributions-length">Emergency arrival patient sampling / distributions / length</h3>
<section id="model" class="level4">
<h4 class="anchored" data-anchor-id="model">Model</h4>
<p>Emergency arrivals (<code>new_patient_traj</code>):</p>
<ul>
<li><code>add_generator("pt_ed", new_patient_traj, function() rpois(1, I_ED) )</code>
<ul>
<li>Where <code>I_ED  = round(year2min/ed_pt)</code> = 5</li>
</ul></li>
<li>Time with <code>ed_staff</code>: <code>timeout(function() rnorm(1, 20,10))</code> (sample 1 from normal distribution with mean 20 and sd 10)</li>
<li>Probability of stroke: <code>sample(1:2, 1, prob = c(PROB_STROKE, (1-PROB_STROKE) )</code>
<ul>
<li>Where <code>PROB_STROKE = st_pt / ed_pt</code>, which is 750/107700=0.006963788 (so probability 0.007, or 0.7%)</li>
<li>Interestingly, the inter-arrival time calculated for stroke (<code>I_ST  = round(year2min/st_pt)</code>) is not used, and instead, the arrival of stroke patients is based on this probability sampling</li>
</ul></li>
</ul>
<p>Non-stroke patients (<code>nonstroke_traj</code>):</p>
<ul>
<li>Probability of discharge vs ct review: <code>sample(1:2, 1, prob = c(.9, .1))</code> so 0.9 or 90% leave, and then 10% get CT review before leave</li>
<li>Discharge: <code>timeout(1)</code></li>
<li>CT review: <code>timeout(20)</code></li>
</ul>
<p>Stroke patients (<code>stroke_traj</code>):</p>
<ul>
<li>Time with stroke doctor: <code>timeout(function() rnorm(1, 30, 10))</code></li>
<li>CT time: <code>timeout(function() rnorm(1, 20,10))</code></li>
<li>Probability of AIS: <code>sample(1:2, 1, prob = c(PROB_AIS, (1-PROB_AIS)))</code>
<ul>
<li>Where <code>PROB_AIS = ais_pt / st_pt</code> = 450/750 = 0.6 (or 60%)</li>
</ul></li>
<li>Not ais: <code>timeout(1)</code></li>
</ul>
<p>AIS patients:</p>
<ul>
<li>Probability of ECR: <code>sample(1:2, 1, prob = c(PROB_ECR, (1-PROB_ECR))</code>
<ul>
<li>Where <code>PROB_ECR = ecr_pt / ais_pt</code> = 58/450 = 0.1288889 (probability 0.13, or 13%)</li>
</ul></li>
<li>TPA only: <code>timeout(1)</code></li>
</ul>
<p>ECR patients:</p>
<ul>
<li>AngioINR time (uses <code>angio_inr</code>, <code>inr</code>, and 3 <code>angio_staff</code>): <code>timeout(function() rnorm(1, 120,60))</code></li>
</ul>
</section>
<section id="paper" class="level4">
<h4 class="anchored" data-anchor-id="paper">Paper</h4>
<p>“The stroke pathway begins with a new patient in the Emergency Department (ED) and ends with the patient “seizing” an angioINR, an INR and angio staff which represents nurses and technologists. The patient must proceed through a sequence of events chronologically as follows: triage in ED, assessment by the stroke team, CT imaging, assessment for ECR eligibility and lastly, acquiring ECR resources (Figure 1). The decision to proceed to the next event is probabilistic and is acquired from logged data from a Comprehensive Stroke Service in Melbourne, Australia, between 2016 and 17 (Table 1).”<span class="citation" data-cites="huang_optimizing_2019">Huang et al. (<a href="#ref-huang_optimizing_2019" role="doc-biblioref">2019</a>)</span></p>
<p>As it stands, Table 1 just contains the number of resources and patients - but, from this paragraph, it appears it might previously have included some of these probabilities.</p>
<p>I had a look online to see if I could find any pre-prints. I came across a <a href="https://jnis.bmj.com/content/10/Suppl_2/A113.2">poster abstract</a>, but otherwise nothing that could help elucidate this. I also looked for the data from the Comprehensive Stroke Service (although I couldn’t easily come across anything with patient counts, and wasn’t certain this information would definitely be public, so limited search).</p>
<p>I looked the the <a href="https://beta.cloudes.me/loadShare?simId=17588">model on CLOUDES</a>, and this had different parameters (although this might just be illustrative). But, for example:</p>
<ul>
<li>ED arrivals - poisson with IAT 10 and 2 entities per arrival- <em>similar</em> to model (poisson with IAT 5 and 1 entity per arrival)</li>
<li>ED triage - normal mean 15 stdev 5 - <em>differs</em> from model (mean 20 sd 10)</li>
<li>Probability stroke 0.7 (and 99.3 leave) - <em>same</em> as model</li>
<li>Time with stroke doctor normal mean 30 sd 10 - <em>same</em> as model</li>
<li>CT normal mean 20 sd 10 - <em>same</em> as model</li>
<li>AIS probability 15 (and 85 leave) and then LVO probability 60 (and 40 leave) (which is described as probabilitiy true AIS) - <em>differs</em> from model (simply, from those who received the CT, 60% AIS and 40% exit)</li>
<li>ECR probabiltiy 15 (and 85 leave) - <em>differs</em> from model (13% ECR)</li>
<li>AngioINR normal mean 120 sd 60 - <em>same</em> as model</li>
</ul>
<p>However, several of them are the same, so it seems it would be worth running the model with those parameters.</p>
</section>
</section>
<section id="other-patients" class="level3">
<h3 class="anchored" data-anchor-id="other-patients">Other patients</h3>
<section id="model-1" class="level4">
<h4 class="anchored" data-anchor-id="model-1">Model</h4>
<p>Interventional radiology patients (<code>ir_traj</code>):</p>
<ul>
<li><code>add_generator("pt_ir", ir_traj, function() rpois(1, I_IR) )</code>
<ul>
<li>Where <code>I_IR  = round(year2min/ir_pt)</code> = 138</li>
</ul></li>
<li>Angio staff time: <code>timeout(function() rnorm(1, 20,10))</code></li>
<li>AngioINR/IR time (uses <code>angio_inr</code> or <code>angio_ir</code>, plus <code>ir</code> and 3 <code>angio_staff</code>): <code>timeout(function() rnorm(1, 60,30))</code></li>
</ul>
<p>Emergency interventional radiology patients (<code>eir_traj</code>):</p>
<ul>
<li><code>add_generator("pt_eir", eir_traj, priority = 1, function() rpois(1, I_EIR) )</code>
<ul>
<li>Where <code>I_EIR = round(year2min/eir_pt)</code> = 1123</li>
</ul></li>
<li>Angio staff time: <code>timeout(function() rnorm(1, 20,10))</code></li>
<li>AngioINR/IR time (uses <code>angio_inr</code> or <code>angio_ir</code>, plus <code>ir</code> and 3 <code>angio_staff</code>): <code>timeout(function() rnorm(1, 60,30))</code></li>
</ul>
<p>Interventional neuroradiology patients (<code>inr_traj</code>): * <code>add_generator("pt_inr", inr_traj, function() rpois(1, I_INR) )</code> * Where <code>I_INR = round(year2min/inr_pt)</code> = 5054 * Angio staff time: <code>timeout(function() rnorm(1, 20,10))</code> * AngioINR time (uses <code>angio_inr</code>, <code>inr</code> and 3 <code>angio_staff</code>): <code>timeout(function() rnorm(1, 60,30))</code></p>
</section>
<section id="cloudes" class="level4">
<h4 class="anchored" data-anchor-id="cloudes">CLOUDES</h4>
<ul>
<li>Non-emergency IR arrivals - poisson IAT 120 1 entity - <em>differs</em> from model (138)</li>
<li>Emergency IR arrivals - poisson IAT 1120 1 entity - <em>differs</em> from model (1123)</li>
<li>Non-emergency INR arrivals - poisson IAT 5040 1 entity - <em>differs</em> from model (5040)</li>
<li>Time with angio staff: normal mean 20 sd 10 - <em>same</em> as model</li>
<li>Routing to rooms: non-emergency IR check for angio room for IR (which chooses between IR and INR based on shortest queue), non-emergency go into INR queue, doesn’t have route for emergency IR - <em>differs</em> from model but looks like this is due to limitation of software in only letting you choose one patient type or all patients</li>
<li>Angio INR time - normal mean 120 sd 60 - <em>differs</em> from model (mean 60 sd 30) but this again might be limitation of software (only allowing one time length regardless of patient type)</li>
<li>Angio IR time - normal mean 60 sd 30 - <em>same</em> as model</li>
</ul>
</section>
</section>
<section id="reflections-from-this" class="level3">
<h3 class="anchored" data-anchor-id="reflections-from-this">Reflections from this</h3>
<p>Some of these differences appear to be rounding/simplifying numbers, or limitations of the CLOUDES software. However, some are more different. My logic here is that the model code we have is for the app and some parameters differed to the paper - so I’m anticipating it’s possible that some of these other parameters may have differed too (but cannot confirm due to them not being reported in the paper). However, if there’s a chance that the CLOUDES model was based on the paper parameters (rather than app), there’s a chance it could help us match up? This seems unlikely though (given it accompanies the app).</p>
<p>However, the only one of real interest I think (that is not simplification or limitation) is the difference in ED triage time.</p>
</section>
</section>
<section id="varying-ed-triage-length" class="level2">
<h2 class="anchored" data-anchor-id="varying-ed-triage-length">13.00-13.15: Varying ED triage length</h2>
<p>I modified the <code>model.R</code> so I could easily change the ED triage mean and SD, then ran a scenario where these were 15 and 5. However, that didn’t make much difference.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_cloudes.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2A with ED triage from CLOUDES</figcaption>
</figure>
</div>
</section>
<section id="double-check-category-being-presented" class="level2">
<h2 class="anchored" data-anchor-id="double-check-category-being-presented">13.16-13.28: Double check category being presented</h2>
<p>I’m pretty sure I’m presenting the right category (ED), but I looked at presenting wait times from patients in any category, or in each of the other categories.</p>
<p>I temporarily removed the filtering from <code>run_model()</code> and then ran:</p>
<pre><code>baseline &lt;- run_model(seed = SEED)

p1 &lt;- create_plot(baseline,
                  group="resource",
                  title="All patients")
p2 &lt;- create_plot(baseline %&gt;% filter(category == "ed"),
                  group="resource",
                  title="ED")
p3 &lt;- create_plot(baseline %&gt;% filter(category == "ir"),
                  group="resource",
                  title="IR")
p4 &lt;- create_plot(baseline %&gt;% filter(category == "eir"),
                  group="resource",
                  title="EIR")
p5 &lt;- create_plot(baseline %&gt;% filter(category == "inr"),
                  group="resource",
                  title="INR")

# Arrange in a single figure
ggarrange(p1, p2, p3, p4, p5, nrow=1, ncol=5,
          common.legend=TRUE, legend="bottom")
ggsave("fig2a_categories.png", width=18)</code></pre>
<p>This supports that ED is the correct choice (the only other similar is EIR but logically, it does still make sense to be ED, and it doesn’t happen to be that EIR is a great match either, just similar).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_categories.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2A categories</figcaption>
</figure>
</div>
</section>
<section id="double-check-inr-room-options" class="level2">
<h2 class="anchored" data-anchor-id="double-check-inr-room-options">13.39-13.43: Double-check INR room options</h2>
<p>Looks right compared with paper, can’t spot any issues</p>
</section>
<section id="vary-length-of-resources-to-try-to-engineer-results" class="level2">
<h2 class="anchored" data-anchor-id="vary-length-of-resources-to-try-to-engineer-results">13.44-14.10, 14.15-14.45: Vary length of resources to try to engineer results</h2>
<p>I can see what looks wrong in each of the figures and so, one option, is to see if I could easily attempt to engineer the results by varying the parameters slightly, to see what might make it look similar.</p>
<p>Looking at Figure 2A as an example:</p>
<ul>
<li>I have <strong>lower AngioINR</strong> queue density and <strong>no visible angio staff</strong> queues (should be queues)
<ul>
<li>Could try increasing the number of patients accessing the angioINR</li>
</ul></li>
<li>There are <strong>INR queues</strong> (when should be none)
<ul>
<li>Could try either having ED patients not use INR, or having more INR availability</li>
</ul></li>
<li>CT, ED staff and stroke doctor queues are similar</li>
</ul>
<p>I ran a few quick models (3 replications), just to see what comes out.</p>
<p><code>run_model(nsim=3, seed = SEED, ed_pt = 107700*2)</code></p>
<p>Doubled the number of emergency department arrivals. This increased angio INR queue but moved CT and ED staff away from desired. Interestingly, no impact on angio staff.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_doubleed.png" class="img-fluid figure-img"></p>
<figcaption>Double ED</figcaption>
</figure>
</div>
<p><code>run_model(nsim=3, seed = SEED, angio_staff = 3)</code></p>
<p>Reduce number of angio staff to 3 during day, which had large impact on angioINR and INR queues, but still no visible angio staff queue.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_lessangiostaff.png" class="img-fluid figure-img"></p>
<figcaption>Halve angio daytime staff</figcaption>
</figure>
</div>
<p>Double ED AND less staff:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_doubleed_lessangiostaff.png" class="img-fluid figure-img"></p>
<figcaption>Double ED AND less staff</figcaption>
</figure>
</div>
<p>Looking at <code>model.R</code>, these results are coming from the simpy resource itself, so this shouldn’t be due to any issues with the calculation of angio staff resource use.</p>
<p>Some extra suggestions from quick chat with Tom:</p>
<ul>
<li>Increase length of AngioINR appointment</li>
<li>Look at the utilisation (e.g.&nbsp;angio staff utilisation)</li>
</ul>
<p>However, if I just plot angio_staff (without the group by resource), I can see it! It just doesn’t appear in the other plot. I then realised that this is because the angio_staff and INR lines <strong>completely overlap</strong>. If we remove INR from the plot, it starts to look a bit more similar.</p>
<p>Hence, it seems that actually the main difference to the paper is just the angioINR queue.</p>
</section>
<section id="looking-into-figure-2c-and-3c-and-getting-in-text-result-2" class="level2">
<h2 class="anchored" data-anchor-id="looking-into-figure-2c-and-3c-and-getting-in-text-result-2">16.03-16.19: Looking into Figure 2C and 3C, and getting in-text result 2!</h2>
<p>Figure 2C has double the machines but, in the paper, they have no change in angio staff levels, whilst I find that increases. That makes sense - with plenty of machines, the bottleneck is now on having the staff for those machines.</p>
<p>I realised then, from reading back on the paper, that I should have replaced an angioIR machine with an angioINR machine (and not just add an extra angioINR machine).</p>
<blockquote class="blockquote">
<p>“Second, in the “two angioINRs” scenario, the angioIR is replaced with an angioINR, doubling angiography availability for ECR patients.” <span class="citation" data-cites="huang_optimizing_2019">Huang et al. (<a href="#ref-huang_optimizing_2019" role="doc-biblioref">2019</a>)</span></p>
</blockquote>
<p>I changed this in <code>reproduction.qmd</code> (<code>angio_inr=2</code>, <code>angio_ir=0</code>) and re-ran the models for Figure 2 and 3. This fixed the (C) part of those figures to be more similar to the paper.</p>
<p>This then resolved in-text result 3, with a 4.3 minute reduction in the queue length (which is very similar to “4 min less”). Hence, can consider that reproduced at this point!</p>
<div id="d6faabf2" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sys.path.append(<span class="st">'../'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> timings <span class="im">import</span> calculate_times</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Minutes used prior to today</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>used_to_date <span class="op">=</span> <span class="dv">975</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Times from today</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>times <span class="op">=</span> [</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.18'</span>, <span class="st">'09.25'</span>),</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.26'</span>, <span class="st">'09.32'</span>),</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.38'</span>, <span class="st">'09.40'</span>),</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.42'</span>, <span class="st">'10.00'</span>),</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'10.09'</span>, <span class="st">'10.12'</span>),</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'10.31'</span>, <span class="st">'10.36'</span>),</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'10.51'</span>, <span class="st">'12.02'</span>),</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'12.12'</span>, <span class="st">'12.15'</span>),</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.00'</span>, <span class="st">'13.15'</span>),</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.16'</span>, <span class="st">'13.28'</span>),</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.39'</span>, <span class="st">'13.43'</span>),</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.44'</span>, <span class="st">'14.10'</span>),</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'14.15'</span>, <span class="st">'14.45'</span>),</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'16.03'</span>, <span class="st">'16.19'</span>)]</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>calculate_times(used_to_date, times)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time spent today: 218m, or 3h 38m
Total used to date: 1193m, or 19h 53m
Time remaining: 1207m, or 20h 7m
Used 49.7% of 40 hours max</code></pre>
</div>
</div>
</section>
<section id="trying-to-raise-the-angioinr-queues" class="level2">
<h2 class="anchored" data-anchor-id="trying-to-raise-the-angioinr-queues">16.25-17.00: Trying to raise the angioINR queues</h2>
<p>Tried changing length of angio appointments for all non-ED patients to the same as ED patients - definitely not right!</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_lonangio.png" class="img-fluid figure-img"></p>
<figcaption>Longer angio</figcaption>
</figure>
</div>
<p>Shorterning the ED angio appointments to the non-ED length is also not helpful.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_shorteredangio.png" class="img-fluid figure-img"></p>
<figcaption>Shorter ED angio</figcaption>
</figure>
</div>
<p>Then I ran through a bunch of different seeds, to see if that also could explain it. Some do come a little closer than others… though this was only five replications. Should probably repeat this exercise, but with 30 replications!</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig2a_5rep_diffseeds.png" class="img-fluid figure-img"></p>
<figcaption>Different seeds</figcaption>
</figure>
</div>
<pre><code>plot_list &lt;- list()
i &lt;- 0
for (s in seq(0, 800, 50)) {
  i &lt;- i + 1
  baseline &lt;- run_model(nsim=5, seed = s)
  plot_list[[i]] &lt;- create_plot(baseline, group="resource", title="")
}
ggarrange(plotlist=plot_list, common.legend=TRUE, legend="bottom")
ggsave("../logbook/posts/2024_07_10/fig2a_5rep_diffseeds.png", width=20, height=20)</code></pre>
</section>
<section id="timings" class="level2">
<h2 class="anchored" data-anchor-id="timings">Timings</h2>
<div id="a177e03f" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sys.path.append(<span class="st">'../'</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> timings <span class="im">import</span> calculate_times</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Minutes used prior to today</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>used_to_date <span class="op">=</span> <span class="dv">975</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Times from today</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>times <span class="op">=</span> [</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.18'</span>, <span class="st">'09.25'</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.26'</span>, <span class="st">'09.32'</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.38'</span>, <span class="st">'09.40'</span>),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'09.42'</span>, <span class="st">'10.00'</span>),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'10.09'</span>, <span class="st">'10.12'</span>),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'10.31'</span>, <span class="st">'10.36'</span>),</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'10.51'</span>, <span class="st">'12.02'</span>),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'12.12'</span>, <span class="st">'12.15'</span>),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.00'</span>, <span class="st">'13.15'</span>),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.16'</span>, <span class="st">'13.28'</span>),</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.39'</span>, <span class="st">'13.43'</span>),</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'13.44'</span>, <span class="st">'14.10'</span>),</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'14.15'</span>, <span class="st">'14.45'</span>),</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'16.03'</span>, <span class="st">'16.19'</span>),</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'16.25'</span>, <span class="st">'17.00'</span>)]</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>calculate_times(used_to_date, times)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time spent today: 253m, or 4h 13m
Total used to date: 1228m, or 20h 28m
Time remaining: 1172m, or 19h 32m
Used 51.2% of 40 hours max</code></pre>
</div>
</div>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-huang_optimizing_2019" class="csl-entry" role="listitem">
Huang, Shiwei, Julian Maingard, Hong Kuan Kok, Christen D. Barras, Vincent Thijs, Ronil V. Chandra, Duncan Mark Brooks, and Hamed Asadi. 2019. <span>“Optimizing <span>Resources</span> for <span>Endovascular</span> <span>Clot</span> <span>Retrieval</span> for <span>Acute</span> <span>Ischemic</span> <span>Stroke</span>, a <span>Discrete</span> <span>Event</span> <span>Simulation</span>.”</span> <em>Frontiers in Neurology</em> 10 (June). <a href="https://doi.org/10.3389/fneur.2019.00653">https://doi.org/10.3389/fneur.2019.00653</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/pythonhealthdatascience\.github\.io\/stars-reproduce-huang-2019\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="https://github.com/pythonhealthdatascience"><img src="https://raw.githubusercontent.com/pythonhealthdatascience/stars-logo/main/stars_logo_blue_text.png" class="img-fluid" alt="STARS" width="300"></a></p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../CHANGELOG.html">
<p>Changelog</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../quarto_site/license.html">
<p>License</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../CONTRIBUTING.html">
<p>Contributing</p>
</a>
  </li>  
</ul>
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/pythonhealthdatascience/stars-reproduce-huang-2019/edit/main/logbook/posts/2024_07_10/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/pythonhealthdatascience/stars-reproduce-huang-2019/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pythonhealthdatascience/stars-reproduce-huang-2019">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>