name: Update GitHub pages
run-name: Render Quarto website and publish on GitHub pages

# Source: https://quarto.org/docs/publishing/github-pages.html
# Source 2: https://github.com/b-rodrigues/rap4all/blob/master/.github/workflows/quarto-publish.yml

on:
# Temporary disable
#  push:
#    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
          uses: r-lib/actions/setup-r@v2
          with:
            r-version: '4.4.1'

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: 'reproduction/'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.353

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Render and publish to GitHub pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
